apiVersion: apps/v1
kind: Deployment
metadata:
  name: embed
  namespace: crypto-trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embed
  template:
    metadata:
      labels:
        app: embed
    spec:
      containers:
        - name: embed
          image: ghcr.io/milesgray/crypto-trading/embed:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: crypto-trading-config
          ports:
            - containerPort: 8301