apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: crypto-trading
spec:
  selector:
    app: portainer
  ports:
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000