apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict
  namespace: crypto-trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
        - name: predict
          image: ghcr.io/milesgray/crypto-trading/predict:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: crypto-trading-config
          ports:
            - containerPort: 8000